name: CI Pipeline

on:
    push:
        branches:
            - develop
            - master

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/setup-node
            - run: npm run format

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/setup-node
            - run: npm run test-coverage

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/setup-node
            - run: npm run build
