name: CI Pipeline

on:
    push:
        branches:
            - develop
            - master

jobs:
    format-check:
        name: Format, Test and Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4

            - name: Install Dependencies
              run: |
                npm i
                npm install -g vite
                npm install -g vitest

            - name: Check Format
              run: npm run format

            - name: Setup .env
              run: |
                touch .env
                echo VITE_APP_URL=http://localhost:5173 >> .env

            - name: Check Tests
              run: npm run test

            - name: Check Build
              run: npm run build
